baseURL = 'http://kulat.co/'
languageCode = 'en-us'
title = 'kulat.co'
theme = 'paper'

# personal configs
[params]
    color = 'gray'
    twitter = 'christiankulat'
    github = 'cdkulat'
    instagram = 'b00lat'

    avatar = 'cdkulat1@gmail.com'
    name = 'Christian Kulat'

monoDarkIcon = true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 10