baseURL = 'http://kulat.co/'
languageCode = 'en-us'
title = 'kulat.co'
theme = 'paper'

# personal configs
[params]
    color = 'gray'
    twitter = 'christiankulat'
    github = 'cdkulat'
    instagram = 'b00lat'
    rss = true

    avatar = 'cdkulat1@gmail.com'
    name = 'Christian Kulat'
    bio = "I'm Christian, a software engineer currently living in the Atlanta area. I've been studying programming for 6 years now, and I'm looking for an opportunity to contribute to your team! My main programming tools are Go and Python - I have enjoy building small scripts, single page applications, testing suites and bots for the online chat and community service Discord. I try and approach these problems by writing the most efficient and beautiful code possible. I'm getting married in October of this year, and in my spare time I love cooking and  playing video games! Thank you for checking out my website. Feel free to reach out to speak about any opportunities you may have. I hope you consider making me a part of your team!"

monoDarkIcon = true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 10